import Foundation

nonisolated enum HermesPluginContent {
  static let pluginName = "supacode-presence"
  static let ownershipMarker = AgentHookSettingsCommand.ownershipMarker

  static let manifestFileName = "plugin.yaml"
  static let moduleFileName = "__init__.py"

  static func manifest() -> String {
    """
    name: \(pluginName)
    version: "1.0.0"
    description: Report Hermes agent presence and turn notifications to Supacode.
    author: Supacode
    hooks:
      - on_session_start
      - pre_llm_call
      - transform_llm_output
      - on_session_end
    provides_hooks:
      - on_session_start
      - pre_llm_call
      - transform_llm_output
      - on_session_end
    """
  }

  /// The two transports and the choice between them, split out of `module()`
  /// so the hook bodies stay readable next to their event names.
  private static let transport = """
    def _write_to_terminal(sequence):
        try:
            fd = os.open("/dev/tty", os.O_WRONLY)
        except OSError:
            return
        try:
            data = sequence.encode("utf-8")
            offset = 0
            while offset < len(data):
                try:
                    written = os.write(fd, data[offset:])
                    if written <= 0:
                        break
                    offset += written
                except (InterruptedError, BlockingIOError):
                    continue
                except OSError:
                    break
        finally:
            os.close(fd)


    def _send_to_socket(path, payload):
        # Returns True only once the app has acked, so a missing, stale, or wedged
        # listener falls through to the terminal instead of swallowing the signal.
        try:
            sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        except OSError:
            return False
        try:
            sock.settimeout(SOCKET_TIMEOUT_SECONDS)
            sock.connect(path)
            sock.sendall(payload.encode("utf-8"))
            # Half-close so the app sees EOF, then drain its ack: leaving it unread
            # makes the app's reply fail with EPIPE.
            sock.shutdown(socket.SHUT_WR)
            while sock.recv(4096):
                pass
            return True
        except OSError:
            return False
        finally:
            sock.close()


    def _signal_socket():
        # The restart-stable name wins: the per-instance path a plugin inherited
        # at spawn stops existing when the app restarts, and falling back to the
        # terminal from inside Hermes corrupts the TUI.
        return os.environ.get("\(AgentPresenceOSC.signalSocketEnvVar)") or os.environ.get(
            "\(AgentPresenceOSC.socketEnvVar)"
        )


    def _emit(action, meta):
        if not _is_supacode_surface():
            return
        path = _signal_socket()
        if path:
            envelope = json.dumps(
                {
                    "\(AgentPresenceOSC.signalField)": AGENT,
                    "\(AgentPresenceOSC.metadataField)": meta,
                    "\(AgentPresenceOSC.surfaceIDField)": os.environ.get("SUPACODE_SURFACE_ID", ""),
                }
            )
            # A configured socket is the transport whether or not the write
            # lands. The plugin runs inside the agent's own process, so falling
            # through would paint an OSC mid-render and corrupt the TUI — worse
            # than the missing badge a dropped signal costs.
            _send_to_socket(path, envelope)
            return
        _write_to_terminal(f"\\x1b]3008;{action}={AGENT};{meta}\\x1b\\\\")
    """

  static func module() -> String {
    """
    \"\"\"Supacode presence bridge for Hermes.\"\"\"

    # \(ownershipMarker)
    # Generated by Supacode. Do not edit. The plugin signals the app over a Unix
    # socket whenever the surface has one, and writes OSC 3008 to Hermes'
    # controlling TTY only when it has none; a socket that is configured but
    # unreachable drops the signal. The plugin runs inside the agent's own
    # process, so a terminal write lands mid-render and corrupts the display.
    # Inert outside Supacode surfaces.

    import base64
    import json
    import os
    import socket

    AGENT = "hermes"
    # Byte caps match the app so the base64 sequence stays under libghostty's 2048-byte OSC ceiling.
    NOTIFY_TITLE_BUDGET = \(AgentPresenceOSC.notifyTitleByteBudget)
    NOTIFY_BODY_BUDGET = \(AgentPresenceOSC.notifyBodyByteBudget)
    SOCKET_TIMEOUT_SECONDS = \(AgentPresenceOSC.socketTimeoutSeconds)


    def register(ctx):
        ctx.register_hook("on_session_start", _on_session_start)
        ctx.register_hook("pre_llm_call", _pre_llm_call)
        ctx.register_hook("transform_llm_output", _transform_llm_output)
        ctx.register_hook("on_session_end", _on_session_end)


    def _is_supacode_surface():
        return bool(os.environ.get("SUPACODE_SURFACE_ID"))


    def _local_pid_suffix():
        # Emitted only when a socket is reachable. Over a forwarded socket the pid
        # belongs to the remote host, so the app decides whether to keep it; on the
        # plain terminal leg there is no way to tell, hence the omission here.
        return f";pid={os.getpid()}" if _signal_socket() else ""


    \(transport)


    def _emit_presence(state):
        action = "end" if state == "session_end" else "start"
        _emit(action, f"event={state}{_local_pid_suffix()}")


    def _notify_field(value, budget):
        escaped = json.dumps(value)[1:-1]
        buf = escaped.encode("utf-8")[:budget]
        return base64.b64encode(buf).decode("ascii")


    def _emit_notification(title, body):
        meta = (
            "kind=notify"
            f";title={_notify_field(title, NOTIFY_TITLE_BUDGET)}"
            f";body={_notify_field(body, NOTIFY_BODY_BUDGET)}"
        )
        _emit("start", meta)


    def _on_session_start(**_kwargs):
        _emit_presence("session_start")


    def _pre_llm_call(**_kwargs):
        _emit_presence("busy")


    def _transform_llm_output(response_text=None, **_kwargs):
        _emit_presence("idle")
        # Coerce defensively: an in-process plugin must never raise into the agent turn.
        body = response_text.strip() if isinstance(response_text, str) else ""
        if body:
            _emit_notification("Hermes", body)
        return None


    def _on_session_end(**_kwargs):
        # on_session_end fires per turn in Hermes, so emit idle (not session_end) to stay present between turns.
        _emit_presence("idle")
    """
  }
}
